ame: publish

on:
  push:
    branches:
    - source
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: build
      uses: github-actions-x/hugo@master
    - name: push
      uses: github-actions-x/commit@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        push_branch: 'master'
        commit_message: 'publish'